name = "TightBindingLattice"
uuid = "f0da6d2f-861b-4198-860c-d50f6f65dfeb"
author = "Kyungmin Lee"
version = "0.1.6"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"

[targets]
test = ["Test"]
example = ["Literate"]
