export FiniteGroup

export group_order
export group_product
export generate_subgroup
export issubgroup
export isabelian
export minimal_generating_set

struct FiniteGroup <: AbstractGroup
    multiplication_table::Matrix{Int}
    period_lengths::Vector{Int}

    function FiniteGroup(mtab::AbstractMatrix{<:Integer})
        n_elem = size(mtab, 1)
        size(mtab, 2) != n_elem && throw(ArgumentError("Multiplication table should be a square matrix"))

        elements = BitSet(1:n_elem)
        mtab[:,1] != 1:n_elem && throw(ArgumentError("Element 1 should be identity"))
        mtab[1,:] != 1:n_elem && throw(ArgumentError("Element 1 should be identity"))
        for i in 2:n_elem
            BitSet(mtab[:,i]) != elements && throw(ArgumentError("Multiplication not a group"))
            BitSet(mtab[i,:]) != elements && throw(ArgumentError("Multiplication not a group"))
        end

        # compute cycles
        period_lengths = zeros(Int, n_elem)
        for idx in 1:n_elem
            jdx = idx
            for i in 1:n_elem
                if jdx == 1
                    period_lengths[idx] = i
                    break
                end
                jdx = mtab[jdx, idx]
            end
        end
        new(mtab, period_lengths)
    end
end


"""
    group_order(group)

Order of group (i.e. number of elements)
"""
group_order(group::FiniteGroup) = size(group.multiplication_table, 1)


"""
    group_order(group, g)

Order of group element (i.e. period length)
"""
group_order(group::FiniteGroup, g::Integer) = group.period_lengths[g]


isabelian(group::FiniteGroup) = group.multiplication_table == transpose(group.multiplication_table)


group_multiplication_table(group::FiniteGroup) = group.multiplication_table


"""
    group_product(group, lhs, rhs)
"""
group_product(group::FiniteGroup, lhs::Integer, rhs::Integer) = group.multiplication_table[lhs, rhs]


function group_product(group::FiniteGroup,
                       lhs::AbstractSet{<:Integer}, rhs::Integer)
    return BitSet([group_product(group, x, rhs) for x in lhs])
end


function group_product(group::FiniteGroup,
                       lhs::Integer, rhs::AbstractSet{<:Integer})
    return BitSet([group_product(group, lhs, x) for x in rhs])
end


function group_product(group::FiniteGroup,
                       lhs::AbstractSet{<:Integer},
                       rhs::AbstractSet{<:Integer})
    return BitSet([group_product(group, x, y) for x in lhs for y in rhs])
end


"""
    generate_subgroup(group, idx)

subgroup generated by `generators`. ⟨ {g} ⟩
"""
function generate_subgroup(group::FiniteGroup, idx::Integer)
    out = BitSet([1])
    jdx = idx
    for i in 1:group_order(group)
        jdx == 1 && return out
        push!(out, jdx)
        jdx = group_product(group, jdx, idx)
    end
    assert(false)
    return BitSet()
end


"""
    generate_subgroup(group, generators)

subgroup generated by `generators`. ⟨ S ⟩
"""
function generate_subgroup(group::FiniteGroup,
                           generators::G) where {G<:Union{<:AbstractSet{<:Integer}, <:AbstractVector{<:Integer}}}
    change = true
    subgroup = BitSet(generators)
    while change
        change = false
        for g1 in generators, g2 in subgroup
            g3 = group_product(group, g1, g2)
            if !(g3 in subgroup)
                change = true
                push!(subgroup, g3)
            end
        end
    end
    return subgroup
end


"""
    generate_subgroup(group, generators...)
"""
function generate_subgroup(group::FiniteGroup, generators::Integer...)
    return generate_subgroup(group, generators)
end


"""
    issubgroup(mtab, subset)
"""
function issubgroup(group::FiniteGroup,
                    subset::AbstractSet{<:Integer})
    return all(group_product(group, x, y) in subset for x in subset for y in subset)
end


"""
    minimal_generating_set
"""
function minimal_generating_set(group::FiniteGroup)
    ord_group ::Int = group_order(group)
    element_queue ::Vector{Tuple{Int, Int}} = collect(enumerate(group.period_lengths))
    sort!(element_queue, by=item->(-item[2], item[1]))

    function factorize(generators::Vector{Int}, span::BitSet, queue_begin::Int)::Bool
        ord_span = length(span)
        ord_span == ord_group && return true
        for i in queue_begin:ord_group
            (g, pl) = element_queue[i]
            if ord_group % (ord_span * pl) == 0
                new_span = generate_subgroup(group, group_product(group, span, g))
                if length(new_span) == ord_span * pl
                    push!(generators, g)
                    factorize(generators, new_span, i+1) && return true
                    pop!(generators)
                end
            end
        end
        return false
    end

    generators = Int[]
    sizehint!(generators, ord_group)
    factorize(generators, BitSet([1]), 1)
    return generators
end


#=
function orthogonalize(group::FiniteGroup)
    !isabelian(group) && throw(ArgumentError("orthogonalize only works for abelian groups"))

    generators = minimal_generating_set(group)
    generator_orders = group.period_lengths[generators]

    elements = Int[1]

    for multiindex in Iterator.product([0:(x-1) for x in generator_orders]...)
        multiindex_vec = [multiindex...]
    end
end
=#
